services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=personal_website_db'
      - 'MYSQL_ROOT_PASSWORD=J5altdwmc'
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql # For persistent data storage
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
volumes:
  db_data:



